"""empty message

Revision ID: 82ab38f6faee
Revises: a4cc90d8b710
Create Date: 2023-03-23 22:46:26.562394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ab38f6faee'
down_revision = 'a4cc90d8b710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrarium_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'terrarium', ['terrarium_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('terrarium_id')

    # ### end Alembic commands ###
