"""empty message

Revision ID: a4cc90d8b710
Revises: 8041ecac9d7c
Create Date: 2023-03-23 00:44:27.364826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4cc90d8b710'
down_revision = '8041ecac9d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('event_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('terrarium_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrarium_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_ibfk_1', 'terrarium', ['terrarium_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=500),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=100),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
